"""upgrade anime db

Revision ID: c754c01223ad
Revises: c7656c265cf5
Create Date: 2024-04-30 14:44:08.485314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c754c01223ad'
down_revision: Union[str, None] = 'c7656c265cf5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('anime', 'title_rus',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('anime', 'title_alt',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('anime', 'rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('anime', 'rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('anime', 'title_alt',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('anime', 'title_rus',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
